services:
  - type: web
    name: apa-formatter-backend
    env: python
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: HF_API_KEY
        sync: false 